config/routes.rb
Rails.application.routes.draw do
    root "support_requests#index"
    resources :support_requests

    get "/search" => "support_requests#search"
    post "/search" => "support_requests#search"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/support_request.rb
class SupportRequest < ApplicationRecord
  before_create :format_name
  after_initialize :set_defaults

  validates :name, presence: true, length: { maximum:50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum:250 },
                                    format: { with: VALID_EMAIL_REGEX }
  enum department: { Sales: 0, Marketing: 1, Technical: 2 }
  validates :message, presence: true, length: { maximum: 2000 }

  scope :search_requests, -> (key = ""){
      where(["name ILIKE ? OR email ILIKE ? OR message ILIKE ?", "%#{key}%", "%#{key}%", "%#{key}%}" ])
      .order("updated_at DESC")}

    private

      def format_name
        self.name = self.name.titleize
      end
      def set_defaults
        self.complete ||= false
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController
  before_action :find_support_request, only: [:show, :edit, :update, :destroy]

  def index
     @support_requests = SupportRequest.order("complete ASC").page(params[:page]).per(7)

     @dep_count = {
      sales:  SupportRequest.where("department = ?", 0).count,
      marketing:      SupportRequest.where("department = ?", 1).count,
      technical:  SupportRequest.where("department = ?", 2).count,
    } #marketing, sales, technical


  end

  def new
    @support_request = SupportRequest.new

  end

  def create
    @support_request = SupportRequest.new(support_request_params)
    if @support_request.save
      flash[:notice] = "Support Request Successfully Submitted"
      redirect_to support_request_path(@support_request)
    else
      flash[:alert] = "Support Request Unsuccessful "
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

    if @support_request.update(support_request_params)
      redirect_to update_success_direction(support_request_params, @support_request), notice: "Support updated"
    else
      flash[:alert] = "Support Request was not updated -- Please check errors below"
      render :edit
    end
  end

  def destroy
    @support_request.destroy
    redirect_to root_path, alert: "Support Request was deleted"
  end



  def search

    if params[:search_term]
     @search_term = params[:search_term]
     @search_results = SupportRequest.search_requests(params[:search_term]).page(params[:page]).per(7)

    end
  end

  private

    def support_request_params
       params.require(:support_request).permit([:name, :email, :department, :message, :complete])
    end

    def find_support_request
      @support_request = SupportRequest.find(params[:id])
    end

    def update_success_direction(params, support_request)
      if support_request_params.has_key?(:complete)
        support_requests_path
      else
        support_request_path(@support_request)
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupportRequests</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container">
        <div class="row">
          <div class="col-xs-12">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<%= root_path %>">Support Request  </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    <li><a href="<%= root_path %>"> ALL </a></li>
                    <li><%= link_to("New", new_support_request_path, {class: "abc"}) %></li>
                  </ul>
                </div><!--/.nav-collapse -->
              </div><!--/.container-fluid -->
            </nav>  <!-- <a href="/about "> About  </a> -->
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/support_requests/_form-request.html.erb
<%= form_for @support_request do |f| %>

  <div class="form-group row">
   <%= f.label(:name, class: "col-xs-2 col-form-label") %>
   <div class="col-xs-10">
     <%= f.text_field :name %>
    </div>
  </div>

  <div class="form-group row">
   <%= f.label(:email, class: "col-xs-2 col-form-label") %>
   <div class="col-xs-10">
     <%= f.text_field :email %>
    </div>
  </div>

  <div class="form-group row">
  <%= f.label(:department, class: "col-xs-2 col-form-label") %>
    <div class="col-xs-10">
      <%= radio_button("support_request", "department", "sales") %> Sales
      <%= radio_button("support_request", "department", "marketing") %> Marketing
      <%= radio_button("support_request", "department", "technical") %> Technical
    </div>

  </div>

  <div class="form-group row">
    <%= f.label(:message, class: "col-xs-2 col-form-label") %>
    <div class="col-xs-10">
    <%= f.text_area :message %>
    </div>
  </div>
  <div class="form-group row">
  <%= f.submit class: "btn btn-success col-xs-offset-2"%>
  </div>



<% end  %>

app/views/support_requests/_search.html.erb
<div class="seach_box">
  <%= form_tag('/search', method: :post) do %>
    <div>
      <%= label_tag :search_term, "Search term" %>
      <%= text_field_tag :search_term , "#@search_term"%>
      <%= submit_tag "Search" , class: "btn btn-default"  %>
    </div>
    <hr>
  <% end %>

  <% if @search_results %>
  <table class="table table-striped">


    <h3></span> Search Results for: "<%= @search_term %>"</h3>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Actions</th>
    </tr>
    <% @search_results.each do |result|  %>
    <tr <% if result.complete %>
       <% else %>
         class="warning"
       <% end %> >
      <td><%= result.name %></td>
      <td><%= result.email %></td>
      <td><%= result.department %></td>
      <td><%= result.message[0..35] %></td>
      <td><%= link_to "Edit", edit_support_request_path(result), class: "btn btn-default btn-xs" %>
            <%= link_to "Delete", support_request_path(result), method: :delete, class: "btn btn-default btn-xs",
            data: { confirm: "Are you sure??" } %>
              <% if result.complete %>
                <%= link_to("Complete",
                     support_request_path(result, "support_request[complete]" => false),
                     class: "btn btn-success btn-xs", method: :put, confirm: { data: "Mark as Complete?"}) %>
              <% else %>
              <%= link_to("Incomplete",
                   support_request_path(result, "support_request[complete]" => true),
                   class: "btn btn-warning btn-xs", method: :put, confirm: { data: "Mark as Incomplete?"}) %>
              <% end %>
      </td>

    </tr>
    <% end %>
  </table>
  <% end %>
</div>

app/views/support_requests/edit.html.erb
<h1>Edit</h1>

<%= render "form-request" %>

app/views/support_requests/index.html.erb
<h1>All Support Requests</h1>

<%= render "search" %>

<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-pills text-right" role="tablist">
      <li>Marketing  <span class="badge"><%= @dep_count[:marketing] %></span></li>
      <li>Sales <span class="badge"><%= @dep_count[:sales] %></span></li>
      <li> Technical <span class="badge"><%= @dep_count[:technical] %></span></li>
    </ul>
  </br>
  </div>
</div>



<div class="row">
  <div class=" col-md-12">

    <table class="table table-striped">
      <tr>
         <th>Name</th>
         <th>Email</th>
         <th>Department</th>
         <th>Message</th>
         <th>Actions</th>
       </tr>
    <% @support_requests.each do |supp| %>
     <tr>
       <td><%= supp.name %></td>
       <td><%= supp.email %></td>
       <td><%= supp.department %></td>
       <td><%= supp.message[0..35] %></td>
       <td><%= link_to "Edit", edit_support_request_path(supp) , class: "btn btn-default btn-xs" %>

             <%= link_to "Delete", support_request_path(supp),
               method: :delete, class: "btn btn-default btn-xs",
               data: { confirm: "Are you sure??" } %>

             <% if supp.complete %>
               <%= link_to("Done",
                    support_request_path(supp, support_request: { complete: false }),
                    method: :put, confirm: { data: "Mark as Complete?"}, class: "btn btn-success btn-xs" ) %>
             <% else %>
             <%= link_to("Undone",
                  support_request_path(supp, support_request: { complete: true }),
                  class: "btn btn-warning btn-xs", method: :put, confirm: { data: "Mark as Incomplete?"}) %>
             <% end %>
       </td>
     </tr>
     <% end %>

    </table>

    <%= paginate @support_requests %>

  </div>
</div>

app/views/support_requests/new.html.erb
<h1>new</h1>

<%= render "form-request" %>

app/views/support_requests/search.html.erb
<h1>Search Results: </h1>

<%= render "search" %>
<%= paginate @search_results %>
<%= page_entries_info @search_results %>

app/views/support_requests/show.html.erb
<h1>Review a Support Request</h1>

<h3>Name: <%= @support_request.name %></h1>
<h3>Email: <%= @support_request.email %></p>
<h4>Department: <%= @support_request.department %></h4>
<p>Message: <%= @support_request.message %></p>
<%= link_to "Edit", edit_support_request_path(@support_request), class: "btn btn-default btn-xs" %>
<%= link_to "Delete", support_request_path(@support_request), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?"} %>